### ISSUE TITLE
Error building for android when repackage.

### ISSUE THREAD

**Issue by SergG90** [nabrozidhs/unity_admob_android#22]
I Installed and adapted your ads plugin to my game and when I try to build for android I get those 2 errors:

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\AndroidSDK\build-tools\22.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/AndroidSDK\platforms\android-22\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.example.games.mainlibproj -S "C:\...\Game\Temp\StagingArea\android-libraries\google-play-services_lib\res"

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\AndroidSDK\build-tools\22.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/AndroidSDK\platforms\android-22\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.example.games.mainlibproj -S "C:\...\Game\Temp\StagingArea\android-libraries\google-play-services_lib\res"

I use last Unity free version.

What can I do? Is a problem of Android SDK or I'm missing something?

**Comment by nabrozidhs** [comment]
I'll give it a try this weekend, in the meantime can you double check that no other library includes the google play services?

**Comment by nabrozidhs** [comment]
Try removing your custom AndroidManifest and start from scratch I had a similar problem after updating the project to the latest Unity3D version.
